num1 = int(input("Inserire il primo numero: "))
num2 = int(input("Inserire il secondo numero: "))

print("Somma =", num1 + num2)
print("Differenza =", num1 - num2)
print("Prodotto =", num1 * num2)
print("Valore medio =", (num1 + num2) / 2)
print("Distanza =", abs(num1 - num2))
print("Valore massimo =", max(num1, num2))
print("Valore minimo =", min(num1, num2))
